include: package:effective_dart/analysis_options.yaml

analyzer:
  errors:
    # Temporary disabled for high code churn
    public_member_api_docs: ignore
    # Actually prefer ALL_CAPS
    constant_identifier_names: ignore

linter:
  rules:
    # Flutter rules not in [effective_dart]
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - package_names
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements

    - always_declare_return_types
    - annotate_overrides
    - avoid_unnecessary_containers
    - avoid_void_async
    - cascade_invocations
    - empty_catches
    #- exhaustive_cases
    - leading_newlines_in_multiline_strings
    - no_duplicate_case_values
    - no_logic_in_create_state
    - only_throw_errors
    - overridden_fields
    - prefer_conditional_assignment
    - prefer_const_declarations
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_for_elements_to_map_fromIterable
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_operator
    - prefer_null_aware_operators
    - prefer_single_quotes
    - provide_deprecation_message
    - recursive_getters
    - sized_box_for_whitespace
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - use_string_buffers

