name: ayso_ks
description: An app to view schedule information for Wichita-area AYSO regions.

repository: https://github.com/skyeskie/ayso_ks

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^4.2.0
  flutter_svg: ^0.19.3 # blocked by flutter_form_builder ^4.2.0
  get_it: ^6.1.1
  getwidget: ^1.2.4
  maps_launcher: ^1.2.2+2 # blocked by tweet_ui (2.4.2)
  photo_view: ^0.10.3 # blocked by tweet_ui (2.4.2)
  sailor: ^0.7.1
  shared_preferences: ">=0.5.8 <2.0.0"
  #sqflite: ^1.3.1
  time: ^2.0.0
  tuple: ^2.0.0
  tweet_ui: ^2.4.2
  twitter_api: ^0.1.2 # may need to replace with dart_twitter_api
  url_launcher: ^5.6.0 # blocked by tweet_ui (2.4.2)
  webview_flutter: ^2.0.4

dependency_overrides:
  date_range_picker: # used by flutter_form_builder
    git:
      url: git://github.com/justkawal/date_range_picker.git
      ref: master
  intl: 0.17.0 # flutter_form_builder @ 4.2.0

dev_dependencies:
  effective_dart: ^1.3.1
  environment_config: ^2.2.5
  flutter_driver_helper:
    git:
      url: git://github.com/skyeskie/flutter_driver_helper.git
      ref: master
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^4.1.3 # blocked by environment_config 2.2.5
  test: any

flutter:
  uses-material-design: true

  assets:
    - img/AYSOKansas.svg
    - img/Fields49.svg
    - img/Fields105.svg
    - img/Fields208.svg
    - img/Fields253.svg
    - img/Fields491.svg
    - img/HomeText.png
    - img/KansasSoccerBall.svg
    - img/MainLogo.png
    - img/osm_region49_1500sq_mk.png
    - img/osm_region105_1500sq_mk.png
    - img/osm_region208_1500sq_mk.png
    - img/osm_region253_1500sq_mk.png
    - img/osm_region491_1500sq_mk.png
    - res/data.json
