name: ayso_ks
description: An app to view schedule information for Wichita-area AYSO regions.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #connectivity
  flutter_form_builder: ^4.2.0
  flutter_svg: ^0.19.3
  get_it: ^6.0.0
  getwidget: ^1.2.4
  photo_view: ^0.11.1
  sailor: ^0.7.1
  shared_preferences: ^2.0.4
  #sqflite: ^1.3.1
  time: ^2.0.0
  tuple: ^1.0.3
  webview_flutter: ^2.0.2

dependency_overrides:
  intl: 0.17.0 # flutter_form_builder @ 4.2.0
  date_range_picker: # used by flutter_form_builder
    git:
      url: git://github.com/justkawal/date_range_picker.git
      ref: master

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3 # Waiting on flutter_svg (0.19.3)

flutter:
  uses-material-design: true

  assets:
    - img/AYSOKansas.svg
    - img/Fields49.svg
    - img/Fields105.svg
    - img/Fields208.svg
    - img/Fields253.svg
    - img/Fields491.svg
    - img/HomeText.png
    - img/KansasSoccerBall.svg
    - img/MainLogo.png
    - img/osm_region49_1500sq.png
    - res/data.json
