name: ayso_ks
description: An app to view schedule information for Wichita-area AYSO regions.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #connectivity
  enum_to_string: ^1.0.9
  flutter_chips_input: ^1.9.0-dev.3
  flutter_form_builder: ^3.11.4
  flutter_icons: ^1.1.0
  flutter_modular: ^1.3.0
  flutter_svg: ^0.18.0
  getwidget: ^1.1.0
  liquid_ui: ^1.0.0+8
  #google_maps_flutter
  photo_view: ^0.9.2
  shared_preferences: ^0.5.8
  #sqflite: ^1.3.1
  time: ^1.3.0
  tuple: ^1.0.3
  webview_flutter: ^0.3.22+1


dev_dependencies:
  effective_dart: ^1.2.3
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test: ">=1.14.0 <1.15.0"

flutter:
  uses-material-design: true

  assets:
    - img/AYSOKansas.svg
    - img/Fields49.svg
    - img/Fields105.svg
    - img/Fields208.svg
    - img/Fields253.svg
    - img/Fields491.svg
    - img/HomeText.png
    - img/KansasSoccerBall.svg
    - img/MainLogo.png
    - img/osm_region49_1500sq.png
    - res/data.json
