name: Flutter CI

on:
  push:
    branches: [ mainline, dev ]

jobs:
  build-analyze-test:
    name: Static analysis and unit/widget testing
    runs-on: ubuntu-latest

    # Maybe add back in?
    #container:
    #  image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        #Temporarily fix to 1.21 version, until flutter_form_builder and FormKey issue resolved
        flutter-version: '1.21.x'
        #channel: 'beta' # ('dev', 'beta', 'stable')
    # Setup
    - name: Install packages
      run: flutter pub get
    # Pre-build generation
    - name: Generate environment keys
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      run: flutter pub run environment_config:generate
    # Static analysis
    - name: Static analysis/linting
      run: flutter analyze
    # Build
    - name: Compilation check
      run: flutter build
    # Tests
    - name: Unit and widget testing
      run: flutter test
